"use client";

/*
 * Centralised EN/FR store for every user-facing string on the site.
 *
 * Switching is pure React state: scroll position, the active section and all
 * pinned ScrollTriggers survive, with no reload. The choice persists in
 * localStorage and is mirrored onto <html lang> for assistive tech.
 *
 * Proper nouns (companies, products, tools, place names) are deliberately
 * NOT translated. French runs longer than English, so copy here is written
 * to fit the same layout rather than translated literally.
 */

import {
  createContext,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react";

export type Lang = "en" | "fr";

type Entry = { en: string; fr: string };

export const DICT: Record<string, Entry> = {
  /* ---------------- nav ---------------- */
  "nav.home": { en: "Home", fr: "Accueil" },
  "nav.about": { en: "About", fr: "À propos" },
  "nav.work": { en: "Work", fr: "Projets" },
  "nav.contact": { en: "Contact", fr: "Contact" },
  "nav.book": { en: "Book a Call", fr: "Réserver un appel" },

  /* ---------------- intro ---------------- */
  "intro.scroll": { en: "Scroll to enter", fr: "Faites défiler pour entrer" },

  /* ---------------- hero ---------------- */
  "hero.kicker": {
    en: "Product Designer & UX Consultant",
    fr: "Product Designer & consultant UX",
  },
  "hero.h1a": { en: "Products that feel", fr: "Des produits qui semblent" },
  "hero.h1aEm": { en: "obvious.", fr: "évidents." },
  "hero.h1b": { en: "Design that", fr: "Un design qui ne l’" },
  "hero.h1bEm": { en: "isn’t.", fr: "est pas." },
  "hero.sub": {
    en: "I design digital products end to end — research, flows, interfaces, systems — with one obsession: making the complex feel effortless.",
    fr: "Je conçois des produits numériques de bout en bout — recherche, parcours, interfaces, systèmes — avec une obsession : rendre le complexe évident.",
  },
  "hero.cta1": { en: "View My Work", fr: "Voir mes projets" },
  "hero.cta2": { en: "See How I Work", fr: "Ma façon de travailler" },
  "hero.scroll": { en: "Scroll to Explore", fr: "Faites défiler" },
  "stat.projects": { en: "Projects Completed", fr: "Projets réalisés" },
  "stat.years": { en: "Years of Experience", fr: "Ans d’expérience" },
  "stat.countries": { en: "Countries Worked With", fr: "Pays collaborés" },
  "stat.satisfaction": { en: "Client Satisfaction", fr: "Satisfaction client" },

  /* ---------------- about ---------------- */
  "about.eyebrow": { en: "About", fr: "À propos" },
  "about.h2a": { en: "Design is how I think —", fr: "Le design, c’est ma façon de penser —" },
  "about.h2b": { en: "business is how I", fr: "le business, ma façon de la" },
  "about.h2Em": { en: "aim", fr: "diriger" },
  "about.h2c": { en: "it.", fr: "." },
  "about.m1": {
    en: "Sophia Antipolis Innovation Hackathon — LockAI",
    fr: "Hackathon Innovation Sophia Antipolis — LockAI",
  },
  "about.m2": {
    en: "Years of cross-functional product experience",
    fr: "Ans d’expérience produit transversale",
  },
  "about.m3": {
    en: "Revenue generated by conversion-focused work",
    fr: "Revenus générés par un travail orienté conversion",
  },
  "about.m4": {
    en: "Tonnes of CO₂ the product I design aims to avoid by 2050",
    fr: "Tonnes de CO₂ que le produit que je conçois vise à éviter d’ici 2050",
  },
  "about.edu": {
    en: "MSc International Business · Montpellier Business School · 2024–2026 · Global Market Intelligence · Strategic Leadership · AI in Business",
    fr: "MSc International Business · Montpellier Business School · 2024–2026 · Intelligence des marchés · Leadership stratégique · IA en entreprise",
  },
  "about.cta": { en: "Explore My Work", fr: "Découvrir mes projets" },

  /* ---------------- journey ---------------- */
  "journey.eyebrow": { en: "My Journey", fr: "Mon parcours" },
  "jr.s1": {
    en: "Roots in sales — Telangana, India",
    fr: "Mes racines dans la vente — Telangana, Inde",
  },
  "jr.s2": {
    en: "Analysis & measurement — France",
    fr: "Analyse & mesure — France",
  },
  "jr.s3": {
    en: "Product Design — Heeding Climate Solutions",
    fr: "Product Design — Heeding Climate Solutions",
  },
  "jr.s4": {
    en: "Enhanced by AI, designed with humans",
    fr: "Augmenté par l’IA, conçu avec des humains",
  },
  "jr.s5": {
    en: "Designing for climate & AI",
    fr: "Concevoir pour le climat & l’IA",
  },

  /* ---------------- design stack ---------------- */
  "stack.eyebrow": { en: "Toolkit", fr: "Outils" },
  "stack.h2": { en: "My Design", fr: "Ma boîte à" },
  "stack.h2Em": { en: "Stack.", fr: "outils." },
  "stack.lede": {
    en: "The tools I use to research, design, prototype, collaborate and ship — from the first rough sketch to production code.",
    fr: "Les outils avec lesquels je recherche, conçois, prototype, collabore et livre — du premier croquis au code en production.",
  },
  "stack.count": { en: "tools", fr: "outils" },
  "stack.disciplines": { en: "disciplines", fr: "disciplines" },

  /* ---------------- work ---------------- */
  "work.eyebrow": { en: "Featured Work", fr: "Projets sélectionnés" },
  "work.h2a": { en: "Selected projects,", fr: "Des projets choisis," },
  "work.h2b": { en: "designed to", fr: "conçus pour être" },
  "work.h2Em": { en: "ship.", fr: "livrés." },
  "work.lede": {
    en: "Product UX, product strategy, data design and systems design — each project a different capability, all one practice.",
    fr: "UX produit, stratégie produit, design de données et de systèmes — chaque projet une compétence différente, une seule pratique.",
  },
  "work.open": { en: "Open case study", fr: "Voir l’étude de cas" },
  "work.hint": { en: "SCROLL TO BROWSE", fr: "FAITES DÉFILER" },

  /* ---------------- experience ---------------- */
  "exp.eyebrow": { en: "Experience", fr: "Expérience" },
  "exp.h2": { en: "Where I built my", fr: "Là où j’ai forgé mon" },
  "exp.h2Em": { en: "judgment.", fr: "jugement." },
  "exp.worked": { en: "What I worked on", fr: "Ce sur quoi j’ai travaillé" },
  "exp.impact": { en: "Impact", fr: "Impact" },
  "exp.tools": { en: "Tools & skills", fr: "Outils & compétences" },
  "exp.hint": { en: "SCROLL · CLICK TO JUMP", fr: "DÉFILER · CLIQUER POUR NAVIGUER" },
  "type.Internship": { en: "Internship", fr: "Stage" },
  "type.Full-time": { en: "Full-time", fr: "Temps plein" },
  "type.Hackathon": { en: "Hackathon", fr: "Hackathon" },
  "type.Freelance": { en: "Freelance", fr: "Freelance" },

  /* ---------------- credentials ---------------- */
  "cert.introLabel": { en: "Introduction", fr: "Introduction" },
  "cert.introTitle1": { en: "VERIFIED", fr: "TITRES" },
  "cert.introTitle2": { en: "CREDENTIALS", fr: "VÉRIFIÉS" },
  "cert.introBody": {
    en: "Continuous, applied learning across data, design, marketing and AI — the technical base underneath the product work.",
    fr: "Un apprentissage continu et appliqué en données, design, marketing et IA — la base technique du travail produit.",
  },
  "cert.introNote": {
    en: "Five programmes · Coursera, LinkedIn Learning and hands-on portfolio projects.",
    fr: "Cinq programmes · Coursera, LinkedIn Learning et projets concrets.",
  },
  "cert.brandRole": { en: "Product Designer", fr: "Product Designer" },
  "cert.issuerTBC": { en: "Issuer — to confirm", fr: "Organisme — à confirmer" },
  "cert.certification": { en: "Certification", fr: "Certification" },
  "cert.verified": { en: "✓ Verified", fr: "✓ Vérifié" },
  "cert.onRequest": { en: "Credential on request", fr: "Justificatif sur demande" },
  "cert.issuedBy": { en: "Issued by", fr: "Délivré par" },
  "cert.year": { en: "Year", fr: "Année" },
  "cert.id": { en: "Credential ID", fr: "N° de justificatif" },
  "cert.tbc": { en: "To confirm", fr: "À confirmer" },
  "cert.skills": { en: "Skills", fr: "Compétences" },
  "cert.verify": { en: "Verify credential ↗", fr: "Vérifier le justificatif ↗" },
  "cert.foot": { en: "Credentials", fr: "Titres" },

  /* ---------------- moments ---------------- */
  "moments.eyebrow": { en: "Moments", fr: "Moments" },
  "moments.h2": { en: "More than just", fr: "Bien plus que du" },
  "moments.h2Em": { en: "design.", fr: "design." },
  "moments.lede": {
    en: "The people, places and late nights that shaped the work — every tile is a chapter.",
    fr: "Les personnes, les lieux et les nuits blanches qui ont façonné le travail — chaque image est un chapitre.",
  },
  "moments.prev": { en: "← Previous", fr: "← Précédent" },
  "moments.next": { en: "Next →", fr: "Suivant →" },
  "moments.soon": { en: "▢  PHOTO COMING SOON", fr: "▢  PHOTO À VENIR" },
  "moments.close": { en: "Close", fr: "Fermer" },

  /* ---------------- connect ---------------- */
  "connect.eyebrow": { en: "Let’s Connect", fr: "Restons en contact" },
  "connect.h2a": { en: "Let’s create what’s", fr: "Créons ce qui" },
  "connect.h2Em": { en: "next.", fr: "vient." },
  "connect.lede": {
    en: "I’m open to product design roles, collaborations and good conversations — if you’re building something people should love, I’d like to hear about it.",
    fr: "Je suis ouvert aux postes en product design, aux collaborations et aux bonnes conversations — si vous construisez quelque chose que les gens devraient adorer, parlons-en.",
  },
  "connect.cta": { en: "Start a Conversation", fr: "Démarrer la conversation" },
  "connect.credit": { en: "Designed & Developed by", fr: "Conçu & développé par" },
  "connect.top": { en: "Back to top ↑", fr: "Haut de page ↑" },

  /* ---------------- case study (/work/[slug]) ---------------- */
  "case.back": { en: "← Back to work", fr: "← Retour aux projets" },
  "case.kicker": { en: "Case Study", fr: "Étude de cas" },
  "case.role": { en: "Role", fr: "Rôle" },
  "case.timeline": { en: "Timeline", fr: "Période" },
  "case.focus": { en: "Focus", fr: "Focus" },
  "case.cover": { en: "COVER", fr: "VISUEL" },
  "case.context": { en: "Context", fr: "Contexte" },
  "case.problem": { en: "The Problem", fr: "Le problème" },
  "case.process": { en: "Process", fr: "Démarche" },
  "case.decisions": { en: "Design Decisions", fr: "Décisions de design" },
  "case.outcome": { en: "Outcome", fr: "Résultats" },
  "case.reflection": { en: "Reflection", fr: "Ce que j’en retire" },
  "case.all": { en: "← All projects", fr: "← Tous les projets" },
  "case.next": { en: "Next project", fr: "Projet suivant" },

  /* ---------------- lab (/tunnel) ---------------- */
  "lab.back": { en: "← PORTFOLIO", fr: "← PORTFOLIO" },
  "lab.hint": {
    en: "LAB · TUNNEL TYPE — SCROLL TO TRAVEL · MOVE THE MOUSE",
    fr: "LAB · TUNNEL TYPE — FAITES DÉFILER POUR AVANCER · BOUGEZ LA SOURIS",
  },

  /* ---------------- 404 ---------------- */
  "nf.label": { en: "404 — NOT FOUND", fr: "404 — PAGE INTROUVABLE" },
  "nf.h1": { en: "This page went", fr: "Cette page a quitté" },
  "nf.h1Em": { en: "off the grid.", fr: "les radars." },
  "nf.cta": { en: "Back to the portfolio →", fr: "Retour au portfolio →" },
};

type Ctx = { lang: Lang; setLang: (l: Lang) => void; t: (k: string) => string };

const LanguageContext = createContext<Ctx>({
  lang: "en",
  setLang: () => {},
  t: (k) => DICT[k]?.en ?? k,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const saved = window.localStorage.getItem("lang") as Lang | null;
    if (saved === "en" || saved === "fr") {
      setLangState(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    try {
      window.localStorage.setItem("lang", l);
    } catch {
      /* private mode — the choice simply won't persist */
    }
    document.documentElement.lang = l;
  };

  const t = (k: string) => DICT[k]?.[lang] ?? DICT[k]?.en ?? k;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);

/** Pick a translated field off a content record: `L(lang, item, "summary")`
 *  returns `item.fr.summary` when available, else the English original. */
export function L<T extends { fr?: Record<string, unknown> }>(
  lang: Lang,
  item: T,
  field: keyof T & string
): string {
  if (lang === "fr" && item.fr && typeof item.fr[field] === "string") {
    return item.fr[field] as string;
  }
  return item[field] as unknown as string;
}
